# Generated by Django 5.2.6 on 2025-11-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
