# Generated by Django 5.2.6 on 2026-04-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_taxpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayment',
            name='package_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
